language: ruby
rvm:
- 2.2
jobs:
  include:
    - stage: build
      install:
        - gem install jekyll
        - gem install jemoji
        - gem install redcarpet
      script: jekyll build
    - stage: test
      install:
        - gem install html-proofer
      script: htmlproof ./_site
    - stage: deploy
      script: cp -r ./_site ./www
      deploy: &gae
        provider: gae
        keyfile: client_secrets.json
        project: benz-io
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_6fb782f0af77_key -iv $encrypted_6fb782f0af77_iv
  -in client_secrets.json.enc -out client_secrets.json -d
