language: ruby
rvm:
- 2.2

install:
  - gem install jekyll jemoji redcarpet html-proofer
script: jekyll build && htmlproofer ./_site
deploy: &gae
  provider: gae
  keyfile: client_secrets.json
  project: benz-io

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_6fb782f0af77_key -iv $encrypted_6fb782f0af77_iv
  -in client_secrets.json.enc -out client_secrets.json -d
