markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
permalink: date
plugins:
  - jemoji

name: Michael Benz
url: http://michael.benz.io
description: UDP, The Honey Badger of the Internet
twitter: megabytemb
exclude: [vendor]
gravatar_url: https://s.gravatar.com/avatar/6c0535ac068ef3bb648b8290de1047a5
google_analytics_tracking_id: UA-23219421-1
