name: Michael Benz
markdown: redcarpet
pygments: true
github: https://www.github.com/megabytemb
urls:
    - text: github
      url: https://github.com/megabytemb
    - text: email
      url: mailto:michael@benz.io
