runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  expiration: 1s
  static_files: _site/index.html
  upload: _site/index.html

- url: /(.*)
  expiration: 1s
  static_files: _site/\1
  upload: _site/(.*)